package cn.edu.bit.gm.sm9.signal;

public enum SignalType {
    AUTHENTICATION_SUCCESS,
    AUTHENTICATION_FAIL,
    MASTER_KEY_SET_SUCCESS,
    MASTER_KEY_INVOKE_SUCCESS,
    MASTER_KEY_SET_FAIL,
    MASTER_KEY_INVOKE_FAIL,
    MASTER_KEY_GET_NULL
}
